ALTER TABLE "Weapon" ADD COLUMN "catalogId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Weapon" ADD COLUMN "automaticDamage" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Character" ADD COLUMN "rulesState" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "Spell" ADD COLUMN "tradition" TEXT NOT NULL DEFAULT '';
