-- Additive migration. Legacy research stays MANUAL until explicitly recalculated.
ALTER TABLE "CustomClass" ADD COLUMN "creationRules" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "Character" ADD COLUMN "acAdjustment" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Domain"
  ADD COLUMN "servicePerFamily" DOUBLE PRECISION NOT NULL DEFAULT 4,
  ADD COLUMN "taxPerFamily" DOUBLE PRECISION NOT NULL DEFAULT 2,
  ADD COLUMN "liturgiesCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "titheCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MagicItemResearch"
  ADD COLUMN "effectType" TEXT NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN "effectCount" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "casterLevel" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN "researchRateGp" DOUBLE PRECISION NOT NULL DEFAULT 50,
  ADD COLUMN "componentCostGp" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "materialCostGp" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "researchCostGp" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "remainingDays" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "hasFormula" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "hasSample" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "knowsEffect" BOOLEAN NOT NULL DEFAULT false;
UPDATE "MagicItemResearch" SET "remainingDays" = "weeksRequired" * 7 WHERE "status" <> 'COMPLETED';
