import {test,expect,type Page} from '@playwright/test'
import {RAW_DEFAULT_CLASSES} from '../../backend/src/utils/seedClasses'
let account:any
async function setup(page:Page){
  if(!account){const name=`classes_${Date.now().toString(36)}`;const response=await page.request.post('/api/auth/register',{data:{username:name,email:`${name}@test.invalid`,password:'browser-test-password',role:'MASTER'}});expect(response.status()).toBe(201);account=await response.json()}
  const headers={authorization:`Bearer ${account.token}`}
  const response=await page.request.post('/api/campaigns',{headers,data:{name:`Classes ${Date.now()}`}})
  expect(response.status()).toBe(201)
  const campaign=await response.json()
  await page.goto('/login');await page.evaluate(({token,user})=>{localStorage.setItem('token',token);localStorage.setItem('user',JSON.stringify(user))},account)
  return {campaign,headers}
}
const builderFor=(page:Page)=>page.locator('details').filter({has:page.getByText('Construir classe por pontos',{exact:true})})

test('catalog normalizes all seeded classes, preserves records and restores master creation',async({page})=>{
  const {campaign,headers}=await setup(page)
  for(const base of RAW_DEFAULT_CLASSES){const response=await page.request.post(`/api/classes/${campaign.id}`,{headers,data:base});expect(response.status(),await response.text()).toBe(201)}
  await page.goto(`/classes?campaignId=${campaign.id}`)
  await expect(page.getByRole('combobox',{name:'Campanha',exact:true})).toHaveValue(campaign.id)
  for(const name of ['Fighter','Elven Spellsword','Dwarven Craftpriest'])await expect(page.getByRole('heading',{name,exact:true})).toHaveCount(1)
  const elf=page.getByRole('button').filter({has:page.getByRole('heading',{name:'Elven Spellsword',exact:true})})
  await expect(elf).toContainText('10 níveis')
  await elf.click();await expect(page.getByRole('row')).toHaveCount(11)
  const catalog=await(await page.request.get(`/api/classes/catalog?campaignId=${campaign.id}`,{headers})).json()
  expect(catalog).toHaveLength(21)
  expect(catalog.every((c:any)=>c.legacyIds.length===1)).toBe(true)
  await page.getByRole('button',{name:'Criar classe',exact:true}).click()
  await expect(builderFor(page).getByLabel('Nome',{exact:true})).toBeVisible()
})

test('creates a class from the catalog and shows current and future powers with hover descriptions',async({page},testInfo)=>{
  const {campaign,headers}=await setup(page)
  await page.goto(`/classes?campaignId=${campaign.id}`)
  await expect(page.getByRole('combobox',{name:'Campanha',exact:true})).toHaveValue(campaign.id)
  await page.getByRole('button',{name:'Criar classe',exact:true}).click()
  const builder=builderFor(page)
  await builder.getByRole('button',{name:'Mostrar opções de Proficiência geral inicial',exact:true}).click()
  const proficiency=builder.getByRole('combobox',{name:'Proficiência geral inicial',exact:true})
  await proficiency.fill('manual of')
  const choices=builder.getByRole('listbox',{name:'Opções de Proficiência geral inicial',exact:true})
  await expect(choices.getByRole('option')).toHaveCount(1)
  await choices.getByText('Manual of Arms',{exact:true}).click()
  await expect(proficiency).toHaveValue('Manual of Arms')
  await builder.getByLabel('Descrição da proficiência inicial',{exact:true}).fill('Reconhece símbolos, equipamentos e patentes militares da terra natal.')
  await builder.getByLabel('Nome',{exact:true}).fill('Fighter')
  await builder.getByLabel('Reduções de armadura',{exact:true}).fill('1')
  await builder.getByRole('button',{name:'Adicionar poder de troca'}).click()
  await builder.getByLabel('Aquisição no nível 1',{exact:true}).selectOption('1-4-10')
  await builder.getByLabel('Nome do poder',{exact:true}).nth(0).fill('Vigília')
  await builder.getByLabel('Descrição do poder',{exact:true}).nth(0).fill('Percebe intrusos durante a vigília.')
  await builder.getByLabel('Nome do poder',{exact:true}).nth(1).fill('Sentinela eterna')
  await builder.getByLabel('Descrição do poder',{exact:true}).nth(1).fill('Protege a fortaleza durante a noite.')
  await builder.getByRole('button',{name:'Conferir construção',exact:true}).click()
  await expect(builder.getByRole('region',{name:'Prévia da classe'})).toBeVisible()
  await page.screenshot({path:testInfo.outputPath('class-builder-desktop.png'),fullPage:true})
  await builder.getByRole('button',{name:'Criar classe na campanha'}).click()
  await expect(builder.getByRole('status')).toContainText('Classe criada')
  const catalog=await(await page.request.get(`/api/classes/catalog?campaignId=${campaign.id}`,{headers})).json()
  const definition=catalog.find((c:any)=>c.source==='campaign'&&c.name==='Fighter')
  expect(definition.powers.find((p:any)=>p.name==='Vigília').minimumLevel).toBe(4)
  const created=await page.request.post('/api/characters/guided',{headers,data:{characterName:'Custom guard',campaignId:campaign.id,classKey:definition.id,str:10,int:10,dex:10,wil:10,con:10,cha:10,hpMax:6}})
  expect(created.status(),await created.text()).toBe(201)
  const character=(await created.json()).character
  await page.goto(`/character/${character.id}`)
  const future=page.locator('details').filter({has:page.getByText('Poderes de níveis futuros',{exact:true})})
  await future.getByText('Poderes de níveis futuros',{exact:true}).click()
  await expect(future).toContainText('Vigília · nível 4')
  await future.getByRole('button',{name:'Ajuda: Vigília',exact:true}).hover()
  await expect(page.getByRole('tooltip')).toContainText('Percebe intrusos')
  expect(await page.locator('body').evaluate(el=>el.scrollWidth<=window.innerWidth)).toBe(true)
  const current=(await(await page.request.get(`/api/characters/${character.id}`,{headers})).json()).character
  expect((await page.request.put(`/api/characters/${character.id}`,{headers,data:{version:current.version,level:4}})).status()).toBe(200)
  await page.reload()
  const active=page.locator('div').filter({has:page.getByRole('heading',{name:'Poderes da Classe',exact:true})}).last()
  await expect(active.getByRole('button',{name:'Ajuda: Vigília',exact:true})).toBeVisible()
  await expect(active.getByRole('button',{name:'Ajuda: Sentinela eterna',exact:true})).toHaveCount(0)
  await expect(page.getByText('Características e restrições',{exact:true})).toHaveCount(0)
})

test('changing a reviewed construction invalidates saving and metadata failures can be retried',async({page},testInfo)=>{
  const {campaign}=await setup(page)
  await page.route('**/api/class-builder/metadata',route=>route.fulfill({status:503,json:{error:'Builder temporarily unavailable'}}))
  await page.goto(`/classes?campaignId=${campaign.id}`)
  await expect(page.getByRole('combobox',{name:'Campanha',exact:true})).toHaveValue(campaign.id)
  await page.getByRole('button',{name:'Criar classe',exact:true}).click()
  const builder=builderFor(page)
  await expect(builder.getByRole('alert')).toContainText('Builder temporarily unavailable')
  await expect(builder.getByRole('button',{name:'Conferir construção',exact:true})).toBeDisabled()
  await page.unroute('**/api/class-builder/metadata')
  await builder.getByRole('button',{name:'Tentar carregar novamente',exact:true}).click()
  await builder.getByLabel('Nome',{exact:true}).fill('Reviewed class')
  await builder.getByRole('button',{name:'Conferir construção',exact:true}).click()
  await expect(builder.getByRole('button',{name:'Criar classe na campanha'})).toBeVisible()
  await builder.getByLabel('Nome',{exact:true}).fill('Changed class')
  await expect(builder.getByRole('button',{name:'Criar classe na campanha'})).toHaveCount(0)
  await page.setViewportSize({width:390,height:844})
  expect(await page.locator('body').evaluate(el=>el.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:testInfo.outputPath('class-builder-mobile.png'),fullPage:true})
  page.once('dialog',dialog=>dialog.dismiss())
  await page.getByRole('link',{name:'Personagens',exact:true}).click()
  await expect(page).toHaveURL(/\/classes\?/)
})
