import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
async function relation(page: Page, headers: Record<string,string>, method: 'post'|'put', path: string, data: any) {
  const id = path.split('/')[3]
  const current = (await (await page.request.get('/api/characters/' + id, {headers})).json()).character
  return page.request[method](path, {headers, data: {...data, version: current.version}})
}

test('registration, campaign, creation, purchase, saving, conflict, export and logout', async ({ page }) => {
  const suffix = Date.now().toString(36)
  const email = `browser_${suffix}@test.invalid`
  await page.goto('/register')
  await page.getByPlaceholder('Seu nome de aventureiro').fill(`browser_${suffix}`)
  await page.getByPlaceholder('seu@email.com').fill(email)
  await page.locator('input[type=password]').fill('browser-test-password')
  await page.getByRole('button', { name: 'Mestre', exact: true }).click()
  await page.getByRole('button', { name: 'Registrar', exact: true }).click()
  await expect(page).toHaveURL(/dashboard$/)
  await page.getByRole('link', { name: 'Campanhas', exact: true }).click()
  await page.getByRole('button', { name: /Nova Campanha/ }).click()
  await page.getByPlaceholder('Nome da Campanha...').fill(`Campaign ${suffix}`)
  await page.getByRole('button', { name: 'Criar', exact: true }).click()
  await expect(page.getByText(`Campaign ${suffix}`, { exact: true })).toBeVisible()
  await page.goto('/characters/new')
  await page.getByLabel(/^Campanha/).selectOption({ label: `Campaign ${suffix}` })
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.getByLabel(/^Classe/).selectOption('catalog:fighter')
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.getByLabel('Nome', { exact: true }).fill(`Ada ${suffix}`)
  await page.getByRole('button', { name: '+ Proficiência', exact: true }).click()
  await page.getByLabel('Nome da proficiência').nth(0).fill('Combat Reflexes')
  await page.getByLabel('Categoria', { exact: true }).nth(0).selectOption('class')
  await page.getByRole('button', { name: '+ Proficiência', exact: true }).click()
  await page.getByLabel('Nome da proficiência').nth(1).fill('Manual of Arms')
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.getByLabel('Moedas de ouro restantes').fill('20')
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar e abrir ficha' }).click()
  await expect(page).toHaveURL(/\/character\//)
  const sheetUrl = page.url()
  const id = new URL(sheetUrl).pathname.split('/').at(-1)
  await page.getByRole('button', { name: 'Inventário & Tesouro', exact: true }).click()
  await page.getByRole('button', { name: /Loja/ }).click()
  const torch = page.locator('[title="Torches (6)"]').locator('../..')
  const purchased = page.waitForResponse(r => r.url().endsWith('/shop/purchase') && r.request().method() === 'POST')
  await torch.getByRole('button', { name: 'Comprar', exact: true }).click()
  expect((await purchased).status()).toBe(201)
  const save = page.waitForResponse(r => r.url().endsWith(`/characters/${id}`) && r.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Salvar', exact: true }).click()
  expect((await save).status()).toBe(200)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Salvar', exact: true })).toBeVisible()
  const token = await page.evaluate(() => localStorage.getItem('token'))
  const headers = { authorization: `Bearer ${token}` }
  const snapshot = (await (await page.request.get(`/api/characters/${id}`, { headers })).json()).character
  expect(snapshot.coinGP).toBe(19)
  const external = await page.request.put(`/api/characters/${id}`, { headers, data: { version: snapshot.version, notes: 'Changed in another session' } })
  expect(external.status()).toBe(200)
  await page.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'A ficha mudou' })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar minhas alterações' }).click()
  const download = await downloadPromise
  const exported = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(JSON.stringify(exported)).toContain(`Ada ${suffix}`)
  expect(JSON.stringify(exported)).not.toContain('passwordHash')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Carregar versão atual' }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'A ficha mudou' })).toHaveCount(0)
  const htmlDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Ficha para impressão/PDF' }).click()
  expect((await htmlDownload).suggestedFilename()).toMatch(/\.html$/)
  await page.getByRole('button', { name: 'Sair', exact: true }).click()
  await expect(page).toHaveURL(/login$/)
  expect((await page.request.get('/api/auth/me', { headers })).status()).toBe(401)
  await page.getByPlaceholder('seu@email.com').fill(email)
  await page.locator('input[type=password]').fill('browser-test-password')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page).toHaveURL(/dashboard$/)
})

test('password recovery presents a neutral confirmation', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('link', { name: 'Esqueci minha senha' }).click()
  await page.getByLabel('E-mail').fill('unknown@test.invalid')
  await page.getByRole('button', { name: 'Enviar link' }).click()
  await expect(page.getByRole('status')).toContainText('Se o e-mail estiver cadastrado')
})

test('rule assistant awards XP, advances HP and settles a domain month',async({page})=>{
  const suffix=`rules_${Date.now().toString(36)}`
  const registration=await page.request.post('/api/auth/register',{data:{username:suffix,email:`${suffix}@test.invalid`,password:'browser-test-password',role:'MASTER'}})
  expect(registration.status()).toBe(201)
  const {token,user}=await registration.json(),headers={authorization:`Bearer ${token}`}
  const created=await page.request.post('/api/characters/guided',{headers,data:{characterName:suffix,classKey:'catalog:fighter',str:10,int:10,dex:10,wil:10,con:10,cha:10,hpMax:6}})
  expect(created.status()).toBe(201)
  const {id}= (await created.json()).character
  expect((await relation(page,headers,'put',`/api/characters/${id}/domain`,{peasantFamilies:100,treasury:1000,garrisonCost:200,liturgiesCost:100,titheCost:100})).status()).toBe(200)
  await page.goto('/login')
  await page.evaluate(({token,user})=>{localStorage.setItem('token',token);localStorage.setItem('user',JSON.stringify(user))},{token,user})
  await page.goto(`/character/${id}`)
  await page.getByRole('button',{name:'Evolução & Regras',exact:true}).click()
  await page.getByLabel('Identificador único da aventura').fill('browser-adventure')
  await page.getByLabel('Valor do tesouro elegível (GP)').fill('2000')
  await page.getByRole('button',{name:'Conferir distribuição de XP'}).click()
  await page.getByRole('button',{name:'Confirmar concessão de XP'}).click()
  await expect(page.getByRole('status')).toContainText('XP concedido')
  await page.getByLabel('Resultados individuais dos dados').fill('8, 7')
  await page.getByRole('button',{name:'Conferir avanço',exact:true}).click()
  await page.getByRole('button',{name:'Confirmar avanço',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Nível atualizado')
  await page.getByRole('button',{name:'Conferir mês',exact:true}).click()
  await page.getByRole('button',{name:'Confirmar fechamento mensal',exact:true}).click()
  await expect(page.getByRole('status').filter({hasText:'Mês registrado'})).toBeVisible()
  const c=(await(await page.request.get(`/api/characters/${id}`,{headers})).json()).character
  expect(c.level).toBe(2);expect(c.hpMax).toBe(15);expect(c.xp).toBe(2000);expect(c.domain.treasury).toBe(1500)
})

test('rule assistant spends a spell and restores it after an acknowledged rest',async({page})=>{
  const suffix=`mage_${Date.now().toString(36)}`
  const registration=await page.request.post('/api/auth/register',{data:{username:suffix,email:`${suffix}@test.invalid`,password:'browser-test-password'}})
  expect(registration.status()).toBe(201)
  const {token,user}=await registration.json(),headers={authorization:`Bearer ${token}`}
  const created=await page.request.post('/api/characters/guided',{headers,data:{characterName:suffix,classKey:'catalog:mage',str:10,int:16,dex:10,wil:10,con:10,cha:10,hpMax:4,spells:[{name:'Slumber',level:1,tradition:'arcane'}]}})
  expect(created.status()).toBe(201)
  const {id}=(await created.json()).character
  await page.goto('/login')
  await page.evaluate(({token,user})=>{localStorage.setItem('token',token);localStorage.setItem('user',JSON.stringify(user))},{token,user})
  await page.goto(`/character/${id}`)
  await page.getByRole('button',{name:'Evolução & Regras',exact:true}).click()
  await page.getByRole('button',{name:'Magia',exact:true}).click()
  await page.getByRole('button',{name:'Conjurar Slumber',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Uso de magia registrado')
  await page.getByLabel(/Foram cumpridas 8 horas/).check()
  await page.getByRole('button',{name:'Registrar descanso',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Usos de magia recuperados')
  const c=(await(await page.request.get(`/api/characters/${id}`,{headers})).json()).character
  expect(JSON.parse(c.rulesState).used).toEqual({})
  const itemResponse=await relation(page,headers,'post',`/api/characters/${id}/items`,{name:'Wand',quantity:1,weight:1/6})
  expect(itemResponse.status()).toBe(201)
  const item=(await itemResponse.json()).item
  await page.reload()
  await page.getByRole('button',{name:'Evolução & Regras',exact:true}).click()
  await page.getByLabel('Item mágico',{exact:true}).selectOption(item.id)
  await page.getByLabel('Identificado em jogo',{exact:true}).check()
  await page.getByLabel('Item com cargas (uma unidade por entrada)',{exact:true}).check()
  await page.getByLabel('Cargas registradas',{exact:true}).fill('2')
  await page.getByRole('button',{name:'Salvar identificação e valores'}).click()
  await expect(page.getByText('Cargas disponíveis: 2',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Ativar e gastar cargas'}).click()
  await expect(page.getByText('Cargas disponíveis: 1',{exact:true})).toBeVisible()
})

test('tracked research consumes components and creates its item through the UI',async({page})=>{
  const suffix=`research_${Date.now().toString(36)}`
  const registration=await page.request.post('/api/auth/register',{data:{username:suffix,email:`${suffix}@test.invalid`,password:'browser-test-password'}})
  expect(registration.status()).toBe(201)
  const {token,user}=await registration.json(),headers={authorization:`Bearer ${token}`}
  const created=await page.request.post('/api/characters/guided',{headers,data:{characterName:suffix,classKey:'catalog:mage',str:10,int:16,dex:10,wil:10,con:10,cha:10,hpMax:4,coinGP:1000}})
  expect(created.status()).toBe(201)
  const c=(await created.json()).character
  expect((await page.request.put(`/api/characters/${c.id}`,{headers,data:{version:c.version,level:5,workshopValue:4000}})).status()).toBe(200)
  const projectResponse=await relation(page,headers,'post',`/api/characters/${c.id}/magic-research`,{itemName:'Test scroll',effectType:'ONE_USE',spellLevel:1,hasFormula:true})
  expect(projectResponse.status()).toBe(201)
  const project=(await projectResponse.json()).research
  const componentResponse=await relation(page,headers,'post',`/api/characters/${c.id}/items`,{name:'Monster component',quantity:1,weight:1})
  const component=(await componentResponse.json()).item
  await page.goto('/login')
  await page.evaluate(({token,user})=>{localStorage.setItem('token',token);localStorage.setItem('user',JSON.stringify(user))},{token,user})
  await page.goto(`/character/${c.id}`)
  await page.getByRole('button',{name:'Evolução & Regras',exact:true}).click()
  await page.getByLabel('Projeto de pesquisa',{exact:true}).selectOption(project.id)
  await page.getByLabel(/Mestre conferiu elegibilidade/).check()
  await page.getByRole('button',{name:'Conferir início da pesquisa'}).click()
  await page.getByRole('button',{name:'Pagar materiais e iniciar'}).click()
  await expect(page.getByRole('status').filter({hasText:'Materiais pagos'})).toBeVisible()
  await page.getByLabel('Período de trabalho (identificador único)').fill('Days 1–10')
  await page.getByLabel('Dias trabalhados',{exact:true}).fill('10')
  await page.getByRole('button',{name:'Registrar trabalho',exact:true}).click()
  await page.getByRole('button',{name:'+ Componente',exact:true}).click()
  await page.getByLabel('Componente',{exact:true}).selectOption(component.id)
  await page.getByLabel('GP/unidade',{exact:true}).fill('500')
  await page.getByRole('button',{name:'Conferir resultado',exact:true}).click()
  await page.getByRole('button',{name:'Consumir componentes e registrar resultado'}).click()
  await expect(page.getByRole('status').filter({hasText:'Resultado registrado'})).toBeVisible()
  const updated=(await(await page.request.get(`/api/characters/${c.id}`,{headers})).json()).character
  expect(updated.coinGP).toBe(500);expect(updated.items.map((i:any)=>i.name)).toContain('Test scroll')
  expect(updated.items.map((i:any)=>i.name)).not.toContain('Monster component')
  await page.getByRole('button',{name:'Magia',exact:true}).click()
  await page.getByText('Aprendizado e pesquisa de magia',{exact:true}).click()
  const trackedRow=page.locator('tr').filter({has:page.getByText('Projeto acompanhado: gerencie em Evolução & Regras.',{exact:true})})
  await expect(trackedRow).toHaveCount(1)
  for(const control of await trackedRow.locator('input, select, button').all()) await expect(control).toBeDisabled()
})

test('campaign master creates a point-built class with a reviewed progression',async({page})=>{
  const suffix=`builder_${Date.now().toString(36)}`
  const registration=await page.request.post('/api/auth/register',{data:{username:suffix,email:`${suffix}@test.invalid`,password:'browser-test-password',role:'MASTER'}})
  expect(registration.status()).toBe(201)
  const {token,user}=await registration.json(),headers={authorization:`Bearer ${token}`}
  const response=await page.request.post('/api/campaigns',{headers,data:{name:suffix}})
  expect(response.status()).toBe(201)
  const campaign=await response.json()
  await page.goto('/login')
  await page.evaluate(({token,user})=>{localStorage.setItem('token',token);localStorage.setItem('user',JSON.stringify(user))},{token,user})
  await page.goto(`/campaigns/${campaign.id}/manage`)
  await page.getByText('Construir classe por pontos',{exact:true}).click()
  const builder=page.locator('details').filter({has:page.getByText('Construir classe por pontos',{exact:true})})
  await builder.getByLabel('Nome',{exact:true}).fill('Reviewed Fighter')
  await builder.getByRole('button',{name:'Conferir construção',exact:true}).click()
  await expect(builder.getByText(/Salva como Fighter/)).toBeVisible()
  await builder.getByRole('button',{name:'Criar classe na campanha'}).click()
  await expect(builder.getByRole('status')).toContainText('Classe criada')
  const classes=await(await page.request.get(`/api/classes/${campaign.id}`,{headers})).json()
  const c=classes.find((c:any)=>c.name==='Reviewed Fighter')
  expect(JSON.parse(c.xpPerLevel)[1]).toBe(2000)
  expect(JSON.parse(c.creationRules).rules.levels).toHaveLength(14)
})
